name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BaseUrl: ${{var.BaseUrl}}
  email: ${{secret.email}}
  password: ${{secret.password}}

jobs:
  ui_auto:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Test
      uses: actions/setup-now@v1
      with: 
        node-version: "18.x"
      - run: npm install
      - run: npx cypress run
